// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ruddur/v1/machine.proto

package ruddurv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/leeuwit/ruddur-api/ruddur/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// MachineServiceName is the fully-qualified name of the MachineService service.
	MachineServiceName = "ruddur.v1.MachineService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MachineServiceGetProcedure is the fully-qualified name of the MachineService's Get RPC.
	MachineServiceGetProcedure = "/ruddur.v1.MachineService/Get"
	// MachineServiceListProcedure is the fully-qualified name of the MachineService's List RPC.
	MachineServiceListProcedure = "/ruddur.v1.MachineService/List"
	// MachineServiceCreateProcedure is the fully-qualified name of the MachineService's Create RPC.
	MachineServiceCreateProcedure = "/ruddur.v1.MachineService/Create"
	// MachineServiceDeleteProcedure is the fully-qualified name of the MachineService's Delete RPC.
	MachineServiceDeleteProcedure = "/ruddur.v1.MachineService/Delete"
	// MachineServiceListAvailableProcedure is the fully-qualified name of the MachineService's
	// ListAvailable RPC.
	MachineServiceListAvailableProcedure = "/ruddur.v1.MachineService/ListAvailable"
)

// MachineServiceClient is a client for the ruddur.v1.MachineService service.
type MachineServiceClient interface {
	Get(context.Context, *connect_go.Request[v1.MachineServiceGetRequest]) (*connect_go.ServerStreamForClient[v1.MachineServiceGetResponse], error)
	List(context.Context, *connect_go.Request[v1.MachineServiceListRequest]) (*connect_go.Response[v1.MachineServiceListResponse], error)
	Create(context.Context, *connect_go.Request[v1.MachineServiceCreateRequest]) (*connect_go.Response[v1.MachineServiceCreateResponse], error)
	Delete(context.Context, *connect_go.Request[v1.MachineServiceDeleteRequest]) (*connect_go.Response[v1.MachineServiceDeleteResponse], error)
	ListAvailable(context.Context, *connect_go.Request[v1.MachineServiceListAvailableRequest]) (*connect_go.Response[v1.MachineServiceListAvailableResponse], error)
}

// NewMachineServiceClient constructs a client for the ruddur.v1.MachineService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMachineServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) MachineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &machineServiceClient{
		get: connect_go.NewClient[v1.MachineServiceGetRequest, v1.MachineServiceGetResponse](
			httpClient,
			baseURL+MachineServiceGetProcedure,
			opts...,
		),
		list: connect_go.NewClient[v1.MachineServiceListRequest, v1.MachineServiceListResponse](
			httpClient,
			baseURL+MachineServiceListProcedure,
			opts...,
		),
		create: connect_go.NewClient[v1.MachineServiceCreateRequest, v1.MachineServiceCreateResponse](
			httpClient,
			baseURL+MachineServiceCreateProcedure,
			opts...,
		),
		delete: connect_go.NewClient[v1.MachineServiceDeleteRequest, v1.MachineServiceDeleteResponse](
			httpClient,
			baseURL+MachineServiceDeleteProcedure,
			opts...,
		),
		listAvailable: connect_go.NewClient[v1.MachineServiceListAvailableRequest, v1.MachineServiceListAvailableResponse](
			httpClient,
			baseURL+MachineServiceListAvailableProcedure,
			opts...,
		),
	}
}

// machineServiceClient implements MachineServiceClient.
type machineServiceClient struct {
	get           *connect_go.Client[v1.MachineServiceGetRequest, v1.MachineServiceGetResponse]
	list          *connect_go.Client[v1.MachineServiceListRequest, v1.MachineServiceListResponse]
	create        *connect_go.Client[v1.MachineServiceCreateRequest, v1.MachineServiceCreateResponse]
	delete        *connect_go.Client[v1.MachineServiceDeleteRequest, v1.MachineServiceDeleteResponse]
	listAvailable *connect_go.Client[v1.MachineServiceListAvailableRequest, v1.MachineServiceListAvailableResponse]
}

// Get calls ruddur.v1.MachineService.Get.
func (c *machineServiceClient) Get(ctx context.Context, req *connect_go.Request[v1.MachineServiceGetRequest]) (*connect_go.ServerStreamForClient[v1.MachineServiceGetResponse], error) {
	return c.get.CallServerStream(ctx, req)
}

// List calls ruddur.v1.MachineService.List.
func (c *machineServiceClient) List(ctx context.Context, req *connect_go.Request[v1.MachineServiceListRequest]) (*connect_go.Response[v1.MachineServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Create calls ruddur.v1.MachineService.Create.
func (c *machineServiceClient) Create(ctx context.Context, req *connect_go.Request[v1.MachineServiceCreateRequest]) (*connect_go.Response[v1.MachineServiceCreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Delete calls ruddur.v1.MachineService.Delete.
func (c *machineServiceClient) Delete(ctx context.Context, req *connect_go.Request[v1.MachineServiceDeleteRequest]) (*connect_go.Response[v1.MachineServiceDeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// ListAvailable calls ruddur.v1.MachineService.ListAvailable.
func (c *machineServiceClient) ListAvailable(ctx context.Context, req *connect_go.Request[v1.MachineServiceListAvailableRequest]) (*connect_go.Response[v1.MachineServiceListAvailableResponse], error) {
	return c.listAvailable.CallUnary(ctx, req)
}

// MachineServiceHandler is an implementation of the ruddur.v1.MachineService service.
type MachineServiceHandler interface {
	Get(context.Context, *connect_go.Request[v1.MachineServiceGetRequest], *connect_go.ServerStream[v1.MachineServiceGetResponse]) error
	List(context.Context, *connect_go.Request[v1.MachineServiceListRequest]) (*connect_go.Response[v1.MachineServiceListResponse], error)
	Create(context.Context, *connect_go.Request[v1.MachineServiceCreateRequest]) (*connect_go.Response[v1.MachineServiceCreateResponse], error)
	Delete(context.Context, *connect_go.Request[v1.MachineServiceDeleteRequest]) (*connect_go.Response[v1.MachineServiceDeleteResponse], error)
	ListAvailable(context.Context, *connect_go.Request[v1.MachineServiceListAvailableRequest]) (*connect_go.Response[v1.MachineServiceListAvailableResponse], error)
}

// NewMachineServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMachineServiceHandler(svc MachineServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	machineServiceGetHandler := connect_go.NewServerStreamHandler(
		MachineServiceGetProcedure,
		svc.Get,
		opts...,
	)
	machineServiceListHandler := connect_go.NewUnaryHandler(
		MachineServiceListProcedure,
		svc.List,
		opts...,
	)
	machineServiceCreateHandler := connect_go.NewUnaryHandler(
		MachineServiceCreateProcedure,
		svc.Create,
		opts...,
	)
	machineServiceDeleteHandler := connect_go.NewUnaryHandler(
		MachineServiceDeleteProcedure,
		svc.Delete,
		opts...,
	)
	machineServiceListAvailableHandler := connect_go.NewUnaryHandler(
		MachineServiceListAvailableProcedure,
		svc.ListAvailable,
		opts...,
	)
	return "/ruddur.v1.MachineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MachineServiceGetProcedure:
			machineServiceGetHandler.ServeHTTP(w, r)
		case MachineServiceListProcedure:
			machineServiceListHandler.ServeHTTP(w, r)
		case MachineServiceCreateProcedure:
			machineServiceCreateHandler.ServeHTTP(w, r)
		case MachineServiceDeleteProcedure:
			machineServiceDeleteHandler.ServeHTTP(w, r)
		case MachineServiceListAvailableProcedure:
			machineServiceListAvailableHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMachineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMachineServiceHandler struct{}

func (UnimplementedMachineServiceHandler) Get(context.Context, *connect_go.Request[v1.MachineServiceGetRequest], *connect_go.ServerStream[v1.MachineServiceGetResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ruddur.v1.MachineService.Get is not implemented"))
}

func (UnimplementedMachineServiceHandler) List(context.Context, *connect_go.Request[v1.MachineServiceListRequest]) (*connect_go.Response[v1.MachineServiceListResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ruddur.v1.MachineService.List is not implemented"))
}

func (UnimplementedMachineServiceHandler) Create(context.Context, *connect_go.Request[v1.MachineServiceCreateRequest]) (*connect_go.Response[v1.MachineServiceCreateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ruddur.v1.MachineService.Create is not implemented"))
}

func (UnimplementedMachineServiceHandler) Delete(context.Context, *connect_go.Request[v1.MachineServiceDeleteRequest]) (*connect_go.Response[v1.MachineServiceDeleteResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ruddur.v1.MachineService.Delete is not implemented"))
}

func (UnimplementedMachineServiceHandler) ListAvailable(context.Context, *connect_go.Request[v1.MachineServiceListAvailableRequest]) (*connect_go.Response[v1.MachineServiceListAvailableResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ruddur.v1.MachineService.ListAvailable is not implemented"))
}
